name: places
description: places
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1

dev_dependencies:
  dart_code_metrics: ^4.21.3
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true
flutter_svg: ^2.0.1

assets:
  - res/

fonts:
  - family: Roboto
    fonts:
      - asset: res/fonts/roboto/*.ttf
